
api:
    # insecure: false
    insecure: true
  
entryPoints:
    web:
        address: ":80"

providers:
    docker:
        # endpoint: "unix:///var/run/docker.sock"
        exposedByDefault: false
        network: proxy
